### ISSUE TITLE
重命名server为httpServer，并增加webSocketServer

### ISSUE THREAD

**Issue by caojiabin2012** [ctfang/Universe#1]
您好，我觉得Universe很不错，想增加他的功能。所以重命名server为httpServer，并增加webSocketServer，您可以看下这是否符合您的想法，如果觉得需要改进可以指点下。代码地址：https://github.com/caojiabin2012/Universe/commit/8cb87d801a7299f511f9b6f81f798e1f03be8f6d
如图：
![image](https://user-images.githubusercontent.com/12596466/38423394-5b74a4b4-39e0-11e8-84fb-16347dcd0f2f.png)

**Comment by ctfang** [comment]
欢迎使用，Universe还有linux定时任务管理小工具https://github.com/ctfang/web-crontab

**Comment by ctfang** [comment]
如果你有兴趣，我可以把你加入开发组有权限提交

**Comment by caojiabin2012** [comment]
可以的，我也是希望代码能提交到主分支上，所以让你看看这些代码是否符合你当初设计思想，哪里不符合，可以指点下我来修改下，如果webSocketServer符合，我也会陆续提交tcpServer和udpServer代码。

**Comment by ctfang** [comment]
发出邀请了，你自己修改README.md，把自己大名加上，我看了你的代码挺不错的，就是把注释改成多行注释，/** */php反射不认识单行注释
